export const FETCH_USERS = "FETCH_USERS";
export const LOGOUT_USER = "LOGOUT_USER";

export const FETCH_QUESTIONS = "FETCH_QUESTIONS";
export const SAVE_QUESTION="SAVE_QUESTION ";
export const SAVE_QUESTION_ANSWER="SAVE_QUESTION_ANSWER ";
export const APPEND_QUESTION_ON_USER="APPEND_QUESTION_ON_USER ";

export const AUTHORIZE_USER = "AUTHORIZE_USER";