export const FETCH_USERS = "FETCH_USERS";
export const LOGOUT_USER = "LOGOUT_USER";

export const FETCH_QUESTIONS = "FETCH_QUESTIONS";
export const SAVE_QUESTION="SAVE_QUESTION ";

export const AUTHORIZE_USER = "AUTHORIZE_USER";